### ISSUE TITLE
Am I missing some config?

### ISSUE THREAD

**Issue by sapg** [delianides/hubot-rackspace#1]
I've added the environment variables but hubot still doesn't seem to know about these commands.  Should I add something to external-scripts.json or hubot-scripts.json?

Thanks.

**Comment by sapg** [comment]
This is what I get when I do that.

[Wed Jul 23 2014 17:34:13 GMT+0000 (GMT)] ERROR Unable to load /opt/hubot/my-bot/node_modules/hubot-rackspace/src/rackspace: ReferenceError: nil is not defined
  at Object.<anonymous> (/opt/hubot/my-bot/node_modules/hubot-rackspace/src/rackspace.coffee:27:9, <js>:14:45)
  at Object.<anonymous> (/opt/hubot/my-bot/node_modules/hubot-rackspace/src/rackspace.coffee:21:1, <js>:152:4)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/opt/hubot/my-bot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/opt/hubot/my-bot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Robot.loadFile (/opt/hubot/my-bot/node_modules/hubot/src/robot.coffee:216:9, <js>:162:11)
  at /opt/hubot/my-bot/node_modules/hubot-rackspace/index.coffee:12:11, <js>:26:33
  at Object.cb [as oncomplete](fs.js:168:19)

**Comment by asheynkman** [comment]
where you able to resolve this issue ?

**Comment by delianides** [comment]
@asheynkman What adapter are you using for hubot?
